name: Node.js CI

on:
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
        working-directory: ./technology-news

      - run: npm run lint
        working-directory: ./technology-news

      - run: npm run build --if-present
        working-directory: ./technology-news
